name: Create Develop to pull request

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Display Branch Name
      run: echo "Current Branch ${{ github.ref }}"

    - name: Check for code changes
      id: code-changes
      run: |
        git fetch origin
        CHANGES=$(git diff HEAD~1 HEAD | wc -c)
        echo "CHANGES=$CHANGES" >> $GITHUB_ENV

    - name: Stop if no code changes
      if: env.CHANGES == '0'
      run: echo "No code changes detected. Exiting..."

    - name: Continue if there are code changes
      if: env.CHANGES != '0'
      run: echo "Code changes detected. Continuing with the workflow..."
